default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['POSTGRES_HOST'] %>
  port: <%= ENV['POSTGRES_PORT'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

development:
 <<: *default
 database: development

test:
 <<: *default
 database: test

production:
 <<: *default
 database: <%= ENV['POSTGRES_NAME'] %>
